### PR TITLE
Support multi-statement destructuring of Ember globals

### PR DESCRIPTION
**Pull request by danwenzel**
Fixes https://github.com/ember-cli/ember-modules-codemod/issues/78#issuecomment-352376538

NOTE:  This only fixes the specific case mentioned in the comment, _not_ the original RSVP case above it.

### CODE REVIEW

**Comment by danwenzel** [comment]
Sounds good!  Looks like CI is now happy :)

**Comment by danwenzel** [comment]
@rwjblue - We good to release this?

**Comment by danwenzel** [comment]
@rwjblue - Pinging again... can we ship this?

**Comment by jkeen** [comment]
This would be a great addition. 🚢

**Comment by rwjblue** [comment]
Thank you! Sorry that it took so long to review!

**Pull request merged**
