### PR TITLE
Namespace support

### LINKED ISSUE #34: Unknown global Ember.inject
_Moved from https://github.com/ember-cli/ember-rfc176-data/issues/34_

If you have inject destructured like this the ember-modules-codemod fails stating this in an unkown global:

`const { inject } = Ember;`

This form of destructing does work:

`const { inject: { service } } = Ember;`

Can/should the first case be supported?

### PR DESCRIPTION
**Pull request by simonihmig**
Fixes #34. Correctly transforms usage of `Ember.computed` and `Ember.inject` namespaces, like:

```js
import Ember from 'ember';
const { inject, computed } = Ember;

export default Ember.Controller.extend({
  controller: inject.controller('application'),
  router: inject.service('router'),
  anotherRouter: computed.alias('router')
});
```

Without this change, this would transform to:

```js
import Controller from '@ember/controller';
import { computed } from '@ember/object';
import Ember from 'ember';
const {
  inject
} = Ember;

export default Controller.extend({
  controller: inject.controller('application'),
  router: inject.service('router'),
  anotherRouter: computed.alias('router')
});
```

After this change:

```js
import { inject as service } from '@ember/service';
import { alias } from '@ember/object/computed';
import Controller, { inject as controller } from '@ember/controller';

export default Controller.extend({
  controller: controller('application'),
  router: service('router'),
  anotherRouter: alias('router')
});
```

Tested on two of our real world code bases that were heavily using patterns like this. 

Also covers the case that the codemod has already been run with some not correctly transformed namespace usages (second example above). Rerunning it on the same app should fix those usages (third example)!

### CODE REVIEW

**Comment by locks** [comment]
It's looking good, thanks for diving into it!

**Comment by Dhaulagiri** [comment]
Thank you @simonihmig!

**Comment by XaserAcheron** [comment]
I finally had the time today to run the codemod for real on my app, and this PR did the trick. Yer a hero, @simonihmig!

**Comment by simonihmig** [comment]
Thanks guys! Did take some time, mostly to understand the existing code, and cover some edge cases. But at the end saved a lot of time for me as well on various code bases, were we had these `computed.something` leftovers...

**Pull request merged**
