### PR TITLE
Add bin test for error reporting

### PR DESCRIPTION
**Pull request by simonihmig**
To prevent things like #75 to happen again!

/cc @Turbo87

### CODE REVIEW

**Comment by Turbo87** [comment]
looks like EOL characters need to be adjusted 🙈

**Comment by simonihmig** [comment]
Oh dear... can't we just drop Windows support? 🙄😝

Will fix this a bit later...

**Comment by simonihmig** [comment]
It was the path separator... Appveyor is happy now, Travis on Linux as well, but seems no free containers left for OSX testing!? (test jobs remain in queue for quite some time)

**Comment by simonihmig** [comment]
Ok, finally green...

**Comment by rwjblue** [comment]
Awesome, thank you!

**Comment by kellyselden** [comment]
Nice work.

**Pull request merged**
