### PR TITLE
use unified line terminator

### PR DESCRIPTION
**Pull request by ro0gr**
see: https://github.com/ember-cli/ember-modules-codemod/issues/44#issuecomment-331267267

### CODE REVIEW

**Comment by ro0gr** [comment]
I think it should be possible to set `eol` dynamically with the help of something like https://www.npmjs.com/package/detect-indent but it's another story.

**Comment by XaserAcheron** [comment]
I'm a bit wary of this change -- wouldn't this cause codemod to convert all `\r\n`s to `\n`s when actually running it on an app? That'll make it practically unusable on projects with `\r\n`s.

I'll test it when I get some time. Busy with another thing at the moment.

**Comment by ro0gr** [comment]
> wouldn't this cause codemod to convert all \r\ns to \n

Yes. It will always use `\n`. I believe that most of the projects use this line endings cause it's a default in `ember-cli` projects.

**Comment by rwjblue** [comment]
Oh dang. Didn't see that last comment. 

Can you test and let us know @xaseracheron?

**Comment by XaserAcheron** [comment]
Yep, confirmed. Running it forces all lines from `\r\n` to `\n\`.

Sorry, guys -- I feel a bit like Pandora here. Guess it's back to the brainstorming-board with this one.

**Pull request merged**
