### PR TITLE
Specify a path

### PR DESCRIPTION
**Pull request by cyril-sf**
I needed to run this on a specific folder while migrating our codebase.

Let me know if you find that useful.

### CODE REVIEW

**Comment by rwjblue** [comment]
I like it, it starts down the path I was trying to layout in https://github.com/ember-cli/ember-modules-codemod/issues/31. 

@cyril-sf - Would you mind double checking that issue to see if we need to make any changes here?

**Comment by cyril-sf** [comment]
I rebased and added a test, just to get this code in a good spot.

I'll take a look at #31 to see what I can do.

**Comment by cyril-sf** [comment]
Failures are unrelated to my code, I'll take a look at it too.

**Comment by cyril-sf** [comment]
```error istanbul-lib-instrument@2.3.2: The engine "node" is incompatible with this module. Expected version ">=6".```

**Comment by rwjblue** [comment]
I _think_ that #87 should have unblocked the testing issue, right?

**Comment by cyril-sf** [comment]
That's my goal/hope. I probably won't have time to finish that today, but will make sure to get this through the finish line before next year 😄

**Comment by rwjblue** [comment]
Thanks again @cyril-sf!

**Comment by cyril-sf** [comment]
Thanks!

I still need to update the README to document that feature.

**Comment by cyril-sf** [comment]
See #89

**Pull request merged**
