### PR TITLE
force git to leave LF line endings

### PR DESCRIPTION
**Pull request by ro0gr**
see https://github.com/ember-cli/ember-modules-codemod/issues/44#issuecomment-330640761

### CODE REVIEW

**Comment by ro0gr** [comment]
I've tested it on my machine with `git config --global core.autocrlf=true`. Seems like line endings are preserved after `git clone` and `git add`.

Also `* text=auto` doesn't do the trick

**Comment by ro0gr** [comment]
@XaserAcheron can you please confirm it works for you?

**Comment by XaserAcheron** [comment]
Works great! It's `\n` all the way down.

Thanks for this!

**Comment by rwjblue** [comment]
Thank you!

**Pull request merged**
