### PR TITLE
Windows Support (for real this time)

### LINKED ISSUE #13: Doesn't work on Windows
```
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1036:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at Object.<anonymous> (D:\npm\node_modules\ember-modules-codemod\bin\ember-modules-codemod.js:24:19)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
```

### PR DESCRIPTION
**Pull request by XaserAcheron**
Closes #13
Closes #38 
Closes #39 

This is mostly @johnunclesam's fixes combined into a single PR, but I've also moved `execa` to dependencies (instead of devDependencies) so installation works properly. Runs just fine on Windows after these changes.

### CODE REVIEW

**Comment by XaserAcheron** [comment]
BTW, I'm not super-sure what the etiquette on including yarn.lock modifications in PRs is (i.e. whether I should include them or let you guys control the update), so let me know if I should take that commit out.

**Comment by johnunclesam** [comment]
I think yarn.lock should be there. Thanks for your work.

**Comment by rwjblue** [comment]
Yes, thank you both very much!! 

Indeed, yarn.lock updates should be included..

**Comment by XaserAcheron** [comment]
Glad to help! And thanks @johnunclesam for doing the real work on this -- forgot to say so in my opening comment, so there it is. ;)

**Comment by rwjblue** [comment]
Awesome, thanks @XaserAcheron and @johnunclesam!

**Pull request merged**
